<a href="https://colab.research.google.com/github/younghwani/begin_tensorflow/blob/master/HiddenLayer2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Library
import pandas as pd
import tensorflow as tf

In [2]:
# prepare data
path = '/content/iris.csv'
iris = pd.read_csv(path)
# One-Hot Encoding
encoding = pd.get_dummies(iris)
# columns 확인
print(encoding.columns)

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')


In [3]:
# set variable
inde = encoding[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
de = encoding[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(inde.shape, de.shape)

(150, 4) (150, 3)


In [4]:
# make model
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8, activation='swish')(X)
H = tf.keras.layers.Dense(8, activation='swish')(H)
H = tf.keras.layers.Dense(8, activation='swish')(H)
Y = tf.keras.layers.Dense(3, activation='softmax')(H)

model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')
# check model
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 4)]               0         
_________________________________________________________________
dense (Dense)                (None, 8)                 40        
_________________________________________________________________
dense_1 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_2 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_3 (Dense)              (None, 3)                 27        
Total params: 211
Trainable params: 211
Non-trainable params: 0
_________________________________________________________________


In [5]:
# fit model
model.fit(inde, de, epochs=300, verbose=0)
model.fit(inde, de, epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0592 - accuracy: 0.9800
Epoch 2/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0649 - accuracy: 0.9867
Epoch 3/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0613 - accuracy: 0.9733
Epoch 4/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0677 - accuracy: 0.9867
Epoch 5/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0714 - accuracy: 0.9667
Epoch 6/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0629 - accuracy: 0.9867
Epoch 7/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0603 - accuracy: 0.9933
Epoch 8/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0646 - accuracy: 0.9800
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0629 - accuracy: 0.9733
Epoch 10/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0605 - accuracy: 0.9867


In [6]:
# use model
print(model.predict(inde[:5]))
print(de[:5])

[[9.9998379e-01 1.6247343e-05 2.4690505e-09]
 [9.9995255e-01 4.7416295e-05 1.2623837e-08]
 [9.9996805e-01 3.1995631e-05 9.8107193e-09]
 [9.9993932e-01 6.0636947e-05 1.7570109e-08]
 [9.9998522e-01 1.4829159e-05 2.3301923e-09]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0
