<a href="https://colab.research.google.com/github/younghwani/begin_tensorflow/blob/master/ModelTip.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Library
import pandas as pd
import tensorflow as tf

# 새로 추가하여 사용할 것
- use
    - tf.keras.layers.BatchNormalization()
    - tf.keras.layers.Activation('swish')

#Iris

In [2]:
# prepare data
path = '/content/iris.csv'
iris = pd.read_csv(path)
# One-Hot Encoding
encoding = pd.get_dummies(iris)
# columns 확인
print(encoding.columns)

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')


In [3]:
# set variable
inde = encoding[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
de = encoding[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(inde.shape, de.shape)

(150, 4) (150, 3)


In [4]:
# make model
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8, activation='swish')(X)
H = tf.keras.layers.Dense(8, activation='swish')(H)
H = tf.keras.layers.Dense(8, activation='swish')(H)
Y = tf.keras.layers.Dense(3, activation='softmax')(H)

model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')
# check model
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 4)]               0         
_________________________________________________________________
dense (Dense)                (None, 8)                 40        
_________________________________________________________________
dense_1 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_2 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_3 (Dense)              (None, 3)                 27        
Total params: 211
Trainable params: 211
Non-trainable params: 0
_________________________________________________________________


In [5]:
# make model use BatchNormalization()
X = tf.keras.layers.Input(shape=[4])

H = tf.keras.layers.Dense(8)(X)
H = tf.keras.layers.Activation('swish')(H)
H = tf.keras.layers.BatchNormalization()(H)

H = tf.keras.layers.Dense(8)(H)
H = tf.keras.layers.Activation('swish')(H)
H = tf.keras.layers.BatchNormalization()(H)

H = tf.keras.layers.Dense(8)(H)
H = tf.keras.layers.Activation('swish')(H)
H = tf.keras.layers.BatchNormalization()(H)

Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')

In [6]:
# fit model
model.fit(inde, de, epochs=1000, batch_size=150, verbose=0)
model.fit(inde, de, epochs=10, batch_size=150)

Epoch 1/10
1/1 [==============================] - 0s 5ms/step - loss: 0.0078 - accuracy: 1.0000
Epoch 2/10
1/1 [==============================] - 0s 6ms/step - loss: 0.0079 - accuracy: 1.0000
Epoch 3/10
1/1 [==============================] - 0s 7ms/step - loss: 0.0078 - accuracy: 1.0000
Epoch 4/10
1/1 [==============================] - 0s 5ms/step - loss: 0.0078 - accuracy: 1.0000
Epoch 5/10
1/1 [==============================] - 0s 5ms/step - loss: 0.0077 - accuracy: 1.0000
Epoch 6/10
1/1 [==============================] - 0s 6ms/step - loss: 0.0078 - accuracy: 1.0000
Epoch 7/10
1/1 [==============================] - 0s 4ms/step - loss: 0.0077 - accuracy: 1.0000
Epoch 8/10
1/1 [==============================] - 0s 5ms/step - loss: 0.0077 - accuracy: 1.0000
Epoch 9/10
1/1 [==============================] - 0s 5ms/step - loss: 0.0077 - accuracy: 1.0000
Epoch 10/10
1/1 [==============================] - 0s 5ms/step - loss: 0.0077 - accuracy: 1.0000


In [7]:
# use model
print(model.predict(inde[:5]))
print(de[:5])

[[9.9998546e-01 1.1196395e-05 3.2795635e-06]
 [9.9996018e-01 3.6057692e-05 3.7651355e-06]
 [9.9998617e-01 4.1682697e-06 9.6968706e-06]
 [9.9998164e-01 1.4385740e-05 3.8815147e-06]
 [9.9998796e-01 6.9173093e-06 5.1854672e-06]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0


#Boston

In [8]:
# Prepare Data
path = '/content/boston.csv'
boston = pd.read_csv(path)
# inde:독립변수, de:종속변수
inde = boston[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat']]
de = boston[['medv']]
#print(inde.shape, de.shape)

In [9]:
# Make Model
X = tf.keras.layers.Input(shape=[13])
H = tf.keras.layers.Dense(8, activation='swish')(X)
H = tf.keras.layers.Dense(8, activation='swish')(H)
H = tf.keras.layers.Dense(8, activation='swish')(H)
Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [10]:
# 위의 방식보다 loss 조금 더 효율적으로 다루기
# BatchNormalization 사용 (Dense layer와 activation layer 사이에 위치하는 것이 효과적)
X = tf.keras.layers.Input(shape=[13])

H = tf.keras.layers.Dense(8)(X)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

H = tf.keras.layers.Dense(8)(H)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

H = tf.keras.layers.Dense(8)(H)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [11]:
# Fit Model
model.fit(inde, de, epochs=1000, verbose=0)
model.fit(inde, de, epochs=10)

Epoch 1/10
16/16 [==============================] - 0s 2ms/step - loss: 9.3392
Epoch 2/10
16/16 [==============================] - 0s 2ms/step - loss: 9.8980
Epoch 3/10
16/16 [==============================] - 0s 2ms/step - loss: 10.8261
Epoch 4/10
16/16 [==============================] - 0s 2ms/step - loss: 11.0518
Epoch 5/10
16/16 [==============================] - 0s 2ms/step - loss: 15.7938
Epoch 6/10
16/16 [==============================] - 0s 2ms/step - loss: 11.6543
Epoch 7/10
16/16 [==============================] - 0s 2ms/step - loss: 10.1682
Epoch 8/10
16/16 [==============================] - 0s 2ms/step - loss: 9.1073
Epoch 9/10
16/16 [==============================] - 0s 2ms/step - loss: 10.1149
Epoch 10/10
16/16 [==============================] - 0s 2ms/step - loss: 9.4060


In [12]:
# Use Model
model.predict(inde[5:10])

array([[24.96086 ],
       [20.548134],
       [19.677195],
       [17.246357],
       [19.138678]], dtype=float32)

In [13]:
de[5:10]

medv
5  28.7
6  22.9
7  27.1
8  16.5
9  18.9

In [14]:
# 모델의 수식 확인
model.get_weights()

[array([[ 3.13474029e-01, -1.32558930e+00,  2.92822897e-01,
         -9.85834599e-02, -9.98463809e-01,  1.37119383e-01,
          2.13817388e-01,  1.22821219e-01],
        [ 5.54187745e-02, -1.85839739e-03, -2.27773800e-01,
          3.94657739e-02, -1.54707000e-01, -6.14731610e-02,
         -6.83088079e-02, -1.98782142e-02],
        [ 5.84541142e-01,  4.01500374e-01,  6.75636828e-01,
          2.06911474e-01, -6.75088048e-01, -2.94491619e-01,
         -1.49016827e-01, -1.40587717e-01],
        [-4.15295303e-01,  2.30479062e-01, -7.05417037e-01,
          1.15826607e+00,  1.87768877e+00, -6.76724553e-01,
         -1.59673238e+00, -4.89953488e-01],
        [-6.31342077e+00,  2.00399208e+00,  7.47378397e+00,
         -2.90047669e+00,  6.22954786e-01, -6.61620498e-01,
          2.97667813e+00,  1.17566860e+00],
        [-1.05938852e+00, -1.03012896e+00,  4.60615098e-01,
          6.45070851e-01, -2.41390228e+00,  2.52414227e+00,
          6.56800032e-01, -2.62615347e+00],
        [ 2.5549